name: Lint Code Base

on: [push, pull_request]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      # From https://github.com/marketplace/actions/lint-action#python-example-flake8-and-black
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Lint Python (Black)
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          # black_dir: ../../ # Run so it can see //pyproject.toml
          black_auto_fix: true

      - uses: actions/checkout@v2
      - name: Run clang-format
        uses: HorstBaerbel/action-clang-format@1.5
        # These are optional (defaults displayed)
        with:
          scandir: '.'
          excludedirs: 'build'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file'
