name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Black (Python)
        uses: psf/black@stable
        with:
          options: |
            --verbose
            --line-length=80
            --exclude /(\.github|\.git|\.venv|\.vscode)/
          src: "."
          version: "22.3.0"
