name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, reopened]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      # From https://github.com/marketplace/actions/lint-action#python-example-flake8-and-black
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Lint Python (Black)
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_dir: ../../ # Run so it can see //pyproject.toml
          black_auto_fix: true

      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v1
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
      - name: Lint C (cpplint)
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
