# Untested!
name: Linux CI Code Base

on: [push, pull_request]

jobs:
  run-linux-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Download cmake
        uses: lukka/get-cmake@latest

      - name: Make ./cmake
        run: mkdir cmake; cd ./cmake; cmake ..; cd ..
      - name: Compile tests
        run: cmake --build cmake
      - name: run tests
        run: ./cmake/src/main && ./cmake/test/test
