name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-linux-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Compile
        run: |
          # For some reason, if we change to the compiler directory, Python complains.
          for x in fibonacci helloworld math_ops nested_if sum_three
          do
            python src/main.py -i examples/$x.lol -o results
            gcc results/$x-*.c
            ./a.out
          done
